using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Workbit.Infrastructure.Database.Entities;

namespace Workbit.Infrastructure.Database.Configuration
{
	public class CountryConfiguration : IEntityTypeConfiguration<Country>
	{
		public void Configure(EntityTypeBuilder<Country> builder)
		{
			builder.HasKey(c => c.Code);

			builder.HasData(SeedCountries());
		}

		private static List<Country> SeedCountries()
		{
			return new List<Country>
			{
new Country { Code = "AD", Name = "Andorra", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "AE", Name = "United Arab Emirates", CurrencyCode = "AED", Continent = "Asia" },
new Country { Code = "AF", Name = "Afghanistan", CurrencyCode = "AFN", Continent = "Asia" },
new Country { Code = "AG", Name = "Antigua and Barbuda", CurrencyCode = "XCD", Continent = "North America" },
new Country { Code = "AI", Name = "Anguilla", CurrencyCode = "XCD", Continent = "North America" },
new Country { Code = "AL", Name = "Albania", CurrencyCode = "ALL", Continent = "Europe" },
new Country { Code = "AM", Name = "Armenia", CurrencyCode = "AMD", Continent = "Asia" },
new Country { Code = "AO", Name = "Angola", CurrencyCode = "AOA", Continent = "Africa" },
new Country { Code = "AQ", Name = "Antarctica", CurrencyCode = "", Continent = "Antarctica" },
new Country { Code = "AR", Name = "Argentina", CurrencyCode = "ARS", Continent = "South America" },
new Country { Code = "AS", Name = "American Samoa", CurrencyCode = "USD", Continent = "Oceania" },
new Country { Code = "AT", Name = "Austria", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "AU", Name = "Australia", CurrencyCode = "AUD", Continent = "Oceania" },
new Country { Code = "AW", Name = "Aruba", CurrencyCode = "AWG", Continent = "North America" },
new Country { Code = "AX", Name = "Åland Islands", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "AZ", Name = "Azerbaijan", CurrencyCode = "AZN", Continent = "Asia" },
new Country { Code = "BA", Name = "Bosnia and Herzegovina", CurrencyCode = "BAM", Continent = "Europe" },
new Country { Code = "BB", Name = "Barbados", CurrencyCode = "BBD", Continent = "North America" },
new Country { Code = "BD", Name = "Bangladesh", CurrencyCode = "BDT", Continent = "Asia" },
new Country { Code = "BE", Name = "Belgium", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "BF", Name = "Burkina Faso", CurrencyCode = "XOF", Continent = "Africa" },
new Country { Code = "BG", Name = "Bulgaria", CurrencyCode = "BGN", Continent = "Europe" },
new Country { Code = "BH", Name = "Bahrain", CurrencyCode = "BHD", Continent = "Asia" },
new Country { Code = "BI", Name = "Burundi", CurrencyCode = "BIF", Continent = "Africa" },
new Country { Code = "BJ", Name = "Benin", CurrencyCode = "XOF", Continent = "Africa" },
new Country { Code = "BL", Name = "Saint Barthélemy", CurrencyCode = "EUR", Continent = "North America" },
new Country { Code = "BM", Name = "Bermuda", CurrencyCode = "BMD", Continent = "North America" },
new Country { Code = "BN", Name = "Brunei Darussalam", CurrencyCode = "BND", Continent = "Asia" },
new Country { Code = "BO", Name = "Bolivia", CurrencyCode = "BOB", Continent = "South America" },
new Country { Code = "BQ", Name = "Bonaire, Sint Eustatius and Saba", CurrencyCode = "USD", Continent = "North America" },
new Country { Code = "BR", Name = "Brazil", CurrencyCode = "BRL", Continent = "South America" },
new Country { Code = "BS", Name = "Bahamas", CurrencyCode = "BSD", Continent = "North America" },
new Country { Code = "BT", Name = "Bhutan", CurrencyCode = "BTN", Continent = "Asia" },
new Country { Code = "BV", Name = "Bouvet Island", CurrencyCode = "NOK", Continent = "Antarctica" },
new Country { Code = "BW", Name = "Botswana", CurrencyCode = "BWP", Continent = "Africa" },
new Country { Code = "BY", Name = "Belarus", CurrencyCode = "BYN", Continent = "Europe" },
new Country { Code = "BZ", Name = "Belize", CurrencyCode = "BZD", Continent = "North America" },
new Country { Code = "CA", Name = "Canada", CurrencyCode = "CAD", Continent = "North America" },
new Country { Code = "CC", Name = "Cocos (Keeling) Islands", CurrencyCode = "AUD", Continent = "Oceania" },
new Country { Code = "CD", Name = "Congo (Democratic Republic)", CurrencyCode = "CDF", Continent = "Africa" },
new Country { Code = "CF", Name = "Central African Republic", CurrencyCode = "XAF", Continent = "Africa" },
new Country { Code = "CG", Name = "Congo", CurrencyCode = "XAF", Continent = "Africa" },
new Country { Code = "CH", Name = "Switzerland", CurrencyCode = "CHF", Continent = "Europe" },
new Country { Code = "CI", Name = "Côte d'Ivoire", CurrencyCode = "XOF", Continent = "Africa" },
new Country { Code = "CK", Name = "Cook Islands", CurrencyCode = "NZD", Continent = "Oceania" },
new Country { Code = "CL", Name = "Chile", CurrencyCode = "CLP", Continent = "South America" },
new Country { Code = "CM", Name = "Cameroon", CurrencyCode = "XAF", Continent = "Africa" },
new Country { Code = "CN", Name = "China", CurrencyCode = "CNY", Continent = "Asia" },
new Country { Code = "CO", Name = "Colombia", CurrencyCode = "COP", Continent = "South America" },
new Country { Code = "CR", Name = "Costa Rica", CurrencyCode = "CRC", Continent = "North America" },
new Country { Code = "CU", Name = "Cuba", CurrencyCode = "CUP", Continent = "North America" },
new Country { Code = "CV", Name = "Cabo Verde", CurrencyCode = "CVE", Continent = "Africa" },
new Country { Code = "CW", Name = "Curaçao", CurrencyCode = "ANG", Continent = "North America" },
new Country { Code = "CX", Name = "Christmas Island", CurrencyCode = "AUD", Continent = "Oceania" },
new Country { Code = "CY", Name = "Cyprus", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "CZ", Name = "Czechia", CurrencyCode = "CZK", Continent = "Europe" },
new Country { Code = "DE", Name = "Germany", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "DJ", Name = "Djibouti", CurrencyCode = "DJF", Continent = "Africa" },
new Country { Code = "DK", Name = "Denmark", CurrencyCode = "DKK", Continent = "Europe" },
new Country { Code = "DM", Name = "Dominica", CurrencyCode = "XCD", Continent = "North America" },
new Country { Code = "DO", Name = "Dominican Republic", CurrencyCode = "DOP", Continent = "North America" },
new Country { Code = "DZ", Name = "Algeria", CurrencyCode = "DZD", Continent = "Africa" },
new Country { Code = "EC", Name = "Ecuador", CurrencyCode = "USD", Continent = "South America" },
new Country { Code = "EE", Name = "Estonia", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "EG", Name = "Egypt", CurrencyCode = "EGP", Continent = "Africa" },
new Country { Code = "EH", Name = "Western Sahara", CurrencyCode = "MAD", Continent = "Africa" },
new Country { Code = "ER", Name = "Eritrea", CurrencyCode = "ERN", Continent = "Africa" },
new Country { Code = "ES", Name = "Spain", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "ET", Name = "Ethiopia", CurrencyCode = "ETB", Continent = "Africa" },
new Country { Code = "FI", Name = "Finland", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "FJ", Name = "Fiji", CurrencyCode = "FJD", Continent = "Oceania" },
new Country { Code = "FK", Name = "Falkland Islands (Malvinas)", CurrencyCode = "FKP", Continent = "South America" },
new Country { Code = "FM", Name = "Micronesia (Federated States)", CurrencyCode = "USD", Continent = "Oceania" },
new Country { Code = "FO", Name = "Faroe Islands", CurrencyCode = "DKK", Continent = "Europe" },
new Country { Code = "FR", Name = "France", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "GA", Name = "Gabon", CurrencyCode = "XAF", Continent = "Africa" },
new Country { Code = "GB", Name = "United Kingdom", CurrencyCode = "GBP", Continent = "Europe" },
new Country { Code = "GD", Name = "Grenada", CurrencyCode = "XCD", Continent = "North America" },
new Country { Code = "GE", Name = "Georgia", CurrencyCode = "GEL", Continent = "Asia" },
new Country { Code = "GF", Name = "French Guiana", CurrencyCode = "EUR", Continent = "South America" },
new Country { Code = "GG", Name = "Guernsey", CurrencyCode = "GBP", Continent = "Europe" },
new Country { Code = "GH", Name = "Ghana", CurrencyCode = "GHS", Continent = "Africa" },
new Country { Code = "GI", Name = "Gibraltar", CurrencyCode = "GIP", Continent = "Europe" },
new Country { Code = "GL", Name = "Greenland", CurrencyCode = "DKK", Continent = "North America" },
new Country { Code = "GM", Name = "Gambia", CurrencyCode = "GMD", Continent = "Africa" },
new Country { Code = "GN", Name = "Guinea", CurrencyCode = "GNF", Continent = "Africa" },
new Country { Code = "GP", Name = "Guadeloupe", CurrencyCode = "EUR", Continent = "North America" },
new Country { Code = "GQ", Name = "Equatorial Guinea", CurrencyCode = "XAF", Continent = "Africa" },
new Country { Code = "GR", Name = "Greece", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "GS", Name = "South Georgia and the South Sandwich Islands", CurrencyCode = "GBP", Continent = "Antarctica" },
new Country { Code = "GT", Name = "Guatemala", CurrencyCode = "GTQ", Continent = "North America" },
new Country { Code = "GU", Name = "Guam", CurrencyCode = "USD", Continent = "Oceania" },
new Country { Code = "GW", Name = "Guinea-Bissau", CurrencyCode = "XOF", Continent = "Africa" },
new Country { Code = "GY", Name = "Guyana", CurrencyCode = "GYD", Continent = "South America" },
new Country { Code = "HK", Name = "Hong Kong", CurrencyCode = "HKD", Continent = "Asia" },
new Country { Code = "HM", Name = "Heard Island and McDonald Islands", CurrencyCode = "AUD", Continent = "Antarctica" },
new Country { Code = "HN", Name = "Honduras", CurrencyCode = "HNL", Continent = "North America" },
new Country { Code = "HR", Name = "Croatia", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "HT", Name = "Haiti", CurrencyCode = "HTG", Continent = "North America" },
new Country { Code = "HU", Name = "Hungary", CurrencyCode = "HUF", Continent = "Europe" },
new Country { Code = "ID", Name = "Indonesia", CurrencyCode = "IDR", Continent = "Asia" },
new Country { Code = "IE", Name = "Ireland", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "IL", Name = "Israel", CurrencyCode = "ILS", Continent = "Asia" },
new Country { Code = "IM", Name = "Isle of Man", CurrencyCode = "GBP", Continent = "Europe" },
new Country { Code = "IN", Name = "India", CurrencyCode = "INR", Continent = "Asia" },
new Country { Code = "IO", Name = "British Indian Ocean Territory", CurrencyCode = "USD", Continent = "Asia" },
new Country { Code = "IQ", Name = "Iraq", CurrencyCode = "IQD", Continent = "Asia" },
new Country { Code = "IR", Name = "Iran", CurrencyCode = "IRR", Continent = "Asia" },
new Country { Code = "IS", Name = "Iceland", CurrencyCode = "ISK", Continent = "Europe" },
new Country { Code = "IT", Name = "Italy", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "JE", Name = "Jersey", CurrencyCode = "GBP", Continent = "Europe" },
new Country { Code = "JM", Name = "Jamaica", CurrencyCode = "JMD", Continent = "North America" },
new Country { Code = "JO", Name = "Jordan", CurrencyCode = "JOD", Continent = "Asia" },
new Country { Code = "JP", Name = "Japan", CurrencyCode = "JPY", Continent = "Asia" },
new Country { Code = "KE", Name = "Kenya", CurrencyCode = "KES", Continent = "Africa" },
new Country { Code = "KG", Name = "Kyrgyzstan", CurrencyCode = "KGS", Continent = "Asia" },
new Country { Code = "KH", Name = "Cambodia", CurrencyCode = "KHR", Continent = "Asia" },
new Country { Code = "KI", Name = "Kiribati", CurrencyCode = "AUD", Continent = "Oceania" },
new Country { Code = "KM", Name = "Comoros", CurrencyCode = "KMF", Continent = "Africa" },
new Country { Code = "KN", Name = "Saint Kitts and Nevis", CurrencyCode = "XCD", Continent = "North America" },
new Country { Code = "KP", Name = "North Korea", CurrencyCode = "KPW", Continent = "Asia" },
new Country { Code = "KR", Name = "South Korea", CurrencyCode = "KRW", Continent = "Asia" },
new Country { Code = "KW", Name = "Kuwait", CurrencyCode = "KWD", Continent = "Asia" },
new Country { Code = "KY", Name = "Cayman Islands", CurrencyCode = "KYD", Continent = "North America" },
new Country { Code = "KZ", Name = "Kazakhstan", CurrencyCode = "KZT", Continent = "Asia" },
new Country { Code = "LA", Name = "Laos", CurrencyCode = "LAK", Continent = "Asia" },
new Country { Code = "LB", Name = "Lebanon", CurrencyCode = "LBP", Continent = "Asia" },
new Country { Code = "LC", Name = "Saint Lucia", CurrencyCode = "XCD", Continent = "North America" },
new Country { Code = "LI", Name = "Liechtenstein", CurrencyCode = "CHF", Continent = "Europe" },
new Country { Code = "LK", Name = "Sri Lanka", CurrencyCode = "LKR", Continent = "Asia" },
new Country { Code = "LR", Name = "Liberia", CurrencyCode = "LRD", Continent = "Africa" },
new Country { Code = "LS", Name = "Lesotho", CurrencyCode = "LSL", Continent = "Africa" },
new Country { Code = "LT", Name = "Lithuania", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "LU", Name = "Luxembourg", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "LV", Name = "Latvia", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "LY", Name = "Libya", CurrencyCode = "LYD", Continent = "Africa" },
new Country { Code = "MA", Name = "Morocco", CurrencyCode = "MAD", Continent = "Africa" },
new Country { Code = "MC", Name = "Monaco", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "MD", Name = "Moldova", CurrencyCode = "MDL", Continent = "Europe" },
new Country { Code = "ME", Name = "Montenegro", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "MF", Name = "Saint Martin (French part)", CurrencyCode = "EUR", Continent = "North America" },
new Country { Code = "MG", Name = "Madagascar", CurrencyCode = "MGA", Continent = "Africa" },
new Country { Code = "MH", Name = "Marshall Islands", CurrencyCode = "USD", Continent = "Oceania" },
new Country { Code = "MK", Name = "North Macedonia", CurrencyCode = "MKD", Continent = "Europe" },
new Country { Code = "ML", Name = "Mali", CurrencyCode = "XOF", Continent = "Africa" },
new Country { Code = "MM", Name = "Myanmar", CurrencyCode = "MMK", Continent = "Asia" },
new Country { Code = "MN", Name = "Mongolia", CurrencyCode = "MNT", Continent = "Asia" },
new Country { Code = "MO", Name = "Macao", CurrencyCode = "MOP", Continent = "Asia" },
new Country { Code = "MP", Name = "Northern Mariana Islands", CurrencyCode = "USD", Continent = "Oceania" },
new Country { Code = "MQ", Name = "Martinique", CurrencyCode = "EUR", Continent = "North America" },
new Country { Code = "MR", Name = "Mauritania", CurrencyCode = "MRU", Continent = "Africa" },
new Country { Code = "MS", Name = "Montserrat", CurrencyCode = "XCD", Continent = "North America" },
new Country { Code = "MT", Name = "Malta", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "MU", Name = "Mauritius", CurrencyCode = "MUR", Continent = "Africa" },
new Country { Code = "MV", Name = "Maldives", CurrencyCode = "MVR", Continent = "Asia" },
new Country { Code = "MW", Name = "Malawi", CurrencyCode = "MWK", Continent = "Africa" },
new Country { Code = "MX", Name = "Mexico", CurrencyCode = "MXN", Continent = "North America" },
new Country { Code = "MY", Name = "Malaysia", CurrencyCode = "MYR", Continent = "Asia" },
new Country { Code = "MZ", Name = "Mozambique", CurrencyCode = "MZN", Continent = "Africa" },
new Country { Code = "NA", Name = "Namibia", CurrencyCode = "NAD", Continent = "Africa" },
new Country { Code = "NC", Name = "New Caledonia", CurrencyCode = "XPF", Continent = "Oceania" },
new Country { Code = "NE", Name = "Niger", CurrencyCode = "XOF", Continent = "Africa" },
new Country { Code = "NF", Name = "Norfolk Island", CurrencyCode = "AUD", Continent = "Oceania" },
new Country { Code = "NG", Name = "Nigeria", CurrencyCode = "NGN", Continent = "Africa" },
new Country { Code = "NI", Name = "Nicaragua", CurrencyCode = "NIO", Continent = "North America" },
new Country { Code = "NL", Name = "Netherlands", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "NO", Name = "Norway", CurrencyCode = "NOK", Continent = "Europe" },
new Country { Code = "NP", Name = "Nepal", CurrencyCode = "NPR", Continent = "Asia" },
new Country { Code = "NR", Name = "Nauru", CurrencyCode = "AUD", Continent = "Oceania" },
new Country { Code = "NU", Name = "Niue", CurrencyCode = "NZD", Continent = "Oceania" },
new Country { Code = "NZ", Name = "New Zealand", CurrencyCode = "NZD", Continent = "Oceania" },
new Country { Code = "OM", Name = "Oman", CurrencyCode = "OMR", Continent = "Asia" },
new Country { Code = "PA", Name = "Panama", CurrencyCode = "PAB", Continent = "North America" },
new Country { Code = "PE", Name = "Peru", CurrencyCode = "PEN", Continent = "South America" },
new Country { Code = "PF", Name = "French Polynesia", CurrencyCode = "XPF", Continent = "Oceania" },
new Country { Code = "PG", Name = "Papua New Guinea", CurrencyCode = "PGK", Continent = "Oceania" },
new Country { Code = "PH", Name = "Philippines", CurrencyCode = "PHP", Continent = "Asia" },
new Country { Code = "PK", Name = "Pakistan", CurrencyCode = "PKR", Continent = "Asia" },
new Country { Code = "PL", Name = "Poland", CurrencyCode = "PLN", Continent = "Europe" },
new Country { Code = "PM", Name = "Saint Pierre and Miquelon", CurrencyCode = "EUR", Continent = "North America" },
new Country { Code = "PN", Name = "Pitcairn", CurrencyCode = "NZD", Continent = "Oceania" },
new Country { Code = "PR", Name = "Puerto Rico", CurrencyCode = "USD", Continent = "North America" },
new Country { Code = "PS", Name = "Palestine, State of", CurrencyCode = "ILS", Continent = "Asia" },
new Country { Code = "PT", Name = "Portugal", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "PW", Name = "Palau", CurrencyCode = "USD", Continent = "Oceania" },
new Country { Code = "PY", Name = "Paraguay", CurrencyCode = "PYG", Continent = "South America" },
new Country { Code = "QA", Name = "Qatar", CurrencyCode = "QAR", Continent = "Asia" },
new Country { Code = "RE", Name = "Réunion", CurrencyCode = "EUR", Continent = "Africa" },
new Country { Code = "RO", Name = "Romania", CurrencyCode = "RON", Continent = "Europe" },
new Country { Code = "RS", Name = "Serbia", CurrencyCode = "RSD", Continent = "Europe" },
new Country { Code = "RU", Name = "Russia", CurrencyCode = "RUB", Continent = "Europe" },
new Country { Code = "RW", Name = "Rwanda", CurrencyCode = "RWF", Continent = "Africa" },
new Country { Code = "SA", Name = "Saudi Arabia", CurrencyCode = "SAR", Continent = "Asia" },
new Country { Code = "SB", Name = "Solomon Islands", CurrencyCode = "SBD", Continent = "Oceania" },
new Country { Code = "SC", Name = "Seychelles", CurrencyCode = "SCR", Continent = "Africa" },
new Country { Code = "SD", Name = "Sudan", CurrencyCode = "SDG", Continent = "Africa" },
new Country { Code = "SE", Name = "Sweden", CurrencyCode = "SEK", Continent = "Europe" },
new Country { Code = "SG", Name = "Singapore", CurrencyCode = "SGD", Continent = "Asia" },
new Country { Code = "SH", Name = "Saint Helena, Ascension and Tristan da Cunha", CurrencyCode = "SHP", Continent = "Africa" },
new Country { Code = "SI", Name = "Slovenia", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "SJ", Name = "Svalbard and Jan Mayen", CurrencyCode = "NOK", Continent = "Europe" },
new Country { Code = "SK", Name = "Slovakia", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "SL", Name = "Sierra Leone", CurrencyCode = "SLL", Continent = "Africa" },
new Country { Code = "SM", Name = "San Marino", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "SN", Name = "Senegal", CurrencyCode = "XOF", Continent = "Africa" },
new Country { Code = "SO", Name = "Somalia", CurrencyCode = "SOS", Continent = "Africa" },
new Country { Code = "SR", Name = "Suriname", CurrencyCode = "SRD", Continent = "South America" },
new Country { Code = "SS", Name = "South Sudan", CurrencyCode = "SSP", Continent = "Africa" },
new Country { Code = "ST", Name = "Sao Tome and Principe", CurrencyCode = "STN", Continent = "Africa" },
new Country { Code = "SV", Name = "El Salvador", CurrencyCode = "USD", Continent = "North America" },
new Country { Code = "SX", Name = "Sint Maarten (Dutch part)", CurrencyCode = "ANG", Continent = "North America" },
new Country { Code = "SY", Name = "Syrian Arab Republic", CurrencyCode = "SYP", Continent = "Asia" },
new Country { Code = "SZ", Name = "Eswatini", CurrencyCode = "SZL", Continent = "Africa" },
new Country { Code = "TC", Name = "Turks and Caicos Islands", CurrencyCode = "USD", Continent = "North America" },
new Country { Code = "TD", Name = "Chad", CurrencyCode = "XAF", Continent = "Africa" },
new Country { Code = "TF", Name = "French Southern Territories", CurrencyCode = "EUR", Continent = "Antarctica" },
new Country { Code = "TG", Name = "Togo", CurrencyCode = "XOF", Continent = "Africa" },
new Country { Code = "TH", Name = "Thailand", CurrencyCode = "THB", Continent = "Asia" },
new Country { Code = "TJ", Name = "Tajikistan", CurrencyCode = "TJS", Continent = "Asia" },
new Country { Code = "TK", Name = "Tokelau", CurrencyCode = "NZD", Continent = "Oceania" },
new Country { Code = "TL", Name = "Timor-Leste", CurrencyCode = "USD", Continent = "Asia" },
new Country { Code = "TM", Name = "Turkmenistan", CurrencyCode = "TMT", Continent = "Asia" },
new Country { Code = "TN", Name = "Tunisia", CurrencyCode = "TND", Continent = "Africa" },
new Country { Code = "TO", Name = "Tonga", CurrencyCode = "TOP", Continent = "Oceania" },
new Country { Code = "TR", Name = "Turkey", CurrencyCode = "TRY", Continent = "Asia" },
new Country { Code = "TT", Name = "Trinidad and Tobago", CurrencyCode = "TTD", Continent = "North America" },
new Country { Code = "TV", Name = "Tuvalu", CurrencyCode = "AUD", Continent = "Oceania" },
new Country { Code = "TW", Name = "Taiwan", CurrencyCode = "TWD", Continent = "Asia" },
new Country { Code = "TZ", Name = "Tanzania", CurrencyCode = "TZS", Continent = "Africa" },
new Country { Code = "UA", Name = "Ukraine", CurrencyCode = "UAH", Continent = "Europe" },
new Country { Code = "UG", Name = "Uganda", CurrencyCode = "UGX", Continent = "Africa" },
new Country { Code = "UM", Name = "United States Minor Outlying Islands", CurrencyCode = "USD", Continent = "Oceania" },
new Country { Code = "US", Name = "United States", CurrencyCode = "USD", Continent = "North America" },
new Country { Code = "UY", Name = "Uruguay", CurrencyCode = "UYU", Continent = "South America" },
new Country { Code = "UZ", Name = "Uzbekistan", CurrencyCode = "UZS", Continent = "Asia" },
new Country { Code = "VA", Name = "Holy See (Vatican City State)", CurrencyCode = "EUR", Continent = "Europe" },
new Country { Code = "VC", Name = "Saint Vincent and the Grenadines", CurrencyCode = "XCD", Continent = "North America" },
new Country { Code = "VE", Name = "Venezuela", CurrencyCode = "VES", Continent = "South America" },
new Country { Code = "VG", Name = "Virgin Islands (British)", CurrencyCode = "USD", Continent = "North America" },
new Country { Code = "VI", Name = "Virgin Islands (U.S.)", CurrencyCode = "USD", Continent = "North America" },
new Country { Code = "VN", Name = "Vietnam", CurrencyCode = "VND", Continent = "Asia" },
new Country { Code = "VU", Name = "Vanuatu", CurrencyCode = "VUV", Continent = "Oceania" },
new Country { Code = "WF", Name = "Wallis and Futuna", CurrencyCode = "XPF", Continent = "Oceania" },
new Country { Code = "WS", Name = "Samoa", CurrencyCode = "WST", Continent = "Oceania" },
new Country { Code = "YE", Name = "Yemen", CurrencyCode = "YER", Continent = "Asia" },
new Country { Code = "YT", Name = "Mayotte", CurrencyCode = "EUR", Continent = "Africa" },
new Country { Code = "ZA", Name = "South Africa", CurrencyCode = "ZAR", Continent = "Africa" },
new Country { Code = "ZM", Name = "Zambia", CurrencyCode = "ZMW", Continent = "Africa" },
new Country { Code = "ZW", Name = "Zimbabwe", CurrencyCode = "ZWL", Continent = "Africa" }
			};
		}
	}
}
